INSERT INTO airlines (airline_name, airline_code)
VALUES ('Alaska Airlines Inc.', 'AS'),
       ('Allegiant Air', 'G4'),
       ('American Airlines Inc.', 'AA'),
       ('Delta Air Lines Inc.', 'DL'),
       ('Endeavor Air Inc.', '9E'),
       ('Envoy Air', 'MQ'),
       ('ExpressJet Airlines LLC d/b/a aha!', 'EV'),
       ('Frontier Airlines Inc.', 'F9'),
       ('Hawaiian Airlines Inc.', 'HA'),
       ('Horizon Air', 'QX'),
       ('JetBlue Airways', 'B6'),
       ('Mesa Airlines Inc.', 'YV'),
       ('PSA Airlines Inc.', 'OH'),
       ('Republic Airline', 'YX'),
       ('SkyWest Airlines Inc.', 'OO'),
       ('Southwest Airlines Co.', 'WN'),
       ('Spirit Air Lines', 'NK'),
       ('United Air Lines Inc.', 'UA');