INSERT INTO airlines (airline_code, airline_name)
VALUES ('HA', 'Hawaiian Airlines Inc.: HA'),
       ('AS', 'Alaska Airlines Inc.: AS'),
       ('WN', 'Southwest Airlines Co.: WN'),
       ('YX', 'Republic Airline: YX'),
       ('AA', 'American Airlines Inc.: AA'),
       ('OH', 'PSA Airlines Inc.: OH'),
       ('EV', 'ExpressJet Airlines LLC d/b/a aha!: EV'),
       ('F9', 'Frontier Airlines Inc.: F9'),
       ('NK', 'Spirit Air Lines: NK'),
       ('OO', 'SkyWest Airlines Inc.: OO'),
       ('UA', 'United Air Lines Inc.: UA'),
       ('DL', 'Delta Air Lines Inc.: DL'),
       ('B6', 'JetBlue Airways: B6'),
       ('QX', 'Horizon Air: QX'),
       ('9E', 'Endeavor Air Inc.: 9E'),
       ('YV', 'Mesa Airlines Inc.: YV'),
       ('G4', 'Allegiant Air: G4'),
       ('MQ', 'Envoy Air: MQ');
